// Package deployssh runs deploy/install.sh on a remote VPS over SSH, non-interactively.
package deployssh

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"net"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/crypto/ssh"
)

const (
	connectTimeout     = 15 * time.Second
	deployTimeout      = 15 * time.Minute
	tcpKeepAlivePeriod = 15 * time.Second

	defaultDeployScriptURL = "https://raw.githubusercontent.com/wlruscfd/openflux-deploy/main/install.sh"
)

// keepaliveInterval is a var, not a const, so tests can shrink it instead of waiting out the real interval.
var keepaliveInterval = 30 * time.Second

// SSHTarget describes how to reach and authenticate to the VPS.
type SSHTarget struct {
	Host     string
	Port     int
	Username string

	// AuthMethod is "password" or "key".
	AuthMethod    string
	Password      string
	PrivateKeyPEM string
	Passphrase    string // only used if PrivateKeyPEM is itself encrypted

	// KnownHostKeyFingerprint pins the server's host key after a first successful connect; leave empty on the first deploy.
	KnownHostKeyFingerprint string
}

type DeployOptions struct {
	DeployScriptURL string

	RepoURL string
	GitRef  string

	TLSMode  string // "domain" or "ip"
	Domain   string
	Email    string
	ServerIP string

	// AdminToken/DBPassword are generated by the caller, not install.sh, so they are known before the deploy starts.
	AdminToken string
	DBPassword string

	RegisterNode bool
	NodeName     string
	NodeMaxKeys  int
	// RunNodeHere, when RegisterNode is true, also builds and runs the exit node on this server as a systemd service.
	RunNodeHere bool
}

// Callback receives live progress from Deploy.
type Callback interface {
	OnLog(line string)
	// OnHostKeyFingerprint is called once after the SSH handshake regardless of KnownHostKeyFingerprint; the caller should persist it.
	OnHostKeyFingerprint(fingerprint string)
	// OnDeployResult fires once with install.sh's summary values; nodeToken is generated remotely and shown only this once.
	OnDeployResult(panelURL, adminToken, nodeToken string)
}

// Deploy blocks until the remote script finishes and returns a non-nil error if it exited non-zero or the connection failed.
func Deploy(target SSHTarget, opts DeployOptions, cb Callback) error {
	if cb == nil {
		cb = noopCallback{}
	}

	authMethod, err := buildAuthMethod(target)
	if err != nil {
		return fmt.Errorf("build ssh auth: %w", err)
	}

	var reportedFingerprint string
	config := &ssh.ClientConfig{
		User:    target.Username,
		Auth:    []ssh.AuthMethod{authMethod},
		Timeout: connectTimeout,
		HostKeyCallback: func(hostname string, remote net.Addr, key ssh.PublicKey) error {
			fp := ssh.FingerprintSHA256(key)
			reportedFingerprint = fp
			if target.KnownHostKeyFingerprint != "" && target.KnownHostKeyFingerprint != fp {
				return fmt.Errorf(
					"host key for %s changed: expected %s, got %s - remove and re-add this server if this is expected (rebuild, reinstall), otherwise treat this as a possible attack and do not proceed",
					hostname, target.KnownHostKeyFingerprint, fp,
				)
			}
			return nil
		},
	}

	addr := net.JoinHostPort(target.Host, strconv.Itoa(target.Port))
	// ssh.Dial leaves TCP keepalive off, so a dead connection could hang silently; the keepalive@openflux goroutine below detects that.
	tcpConn, err := (&net.Dialer{Timeout: connectTimeout, KeepAlive: tcpKeepAlivePeriod}).Dial("tcp", addr)
	if err != nil {
		return fmt.Errorf("dial %s: %w", addr, err)
	}
	sshConn, chans, reqs, err := ssh.NewClientConn(tcpConn, addr, config)
	if err != nil {
		tcpConn.Close()
		return fmt.Errorf("ssh handshake %s: %w", addr, err)
	}
	client := ssh.NewClient(sshConn, chans, reqs)
	defer client.Close()

	cb.OnHostKeyFingerprint(reportedFingerprint)

	stopKeepalive := make(chan struct{})
	defer close(stopKeepalive)
	go func() {
		ticker := time.NewTicker(keepaliveInterval)
		defer ticker.Stop()
		for {
			select {
			case <-stopKeepalive:
				return
			case <-ticker.C:
				client.SendRequest("keepalive@openflux", true, nil)
			}
		}
	}()

	session, err := client.NewSession()
	if err != nil {
		return fmt.Errorf("open ssh session: %w", err)
	}
	defer session.Close()

	stdout, err := session.StdoutPipe()
	if err != nil {
		return fmt.Errorf("stdout pipe: %w", err)
	}
	stderr, err := session.StderrPipe()
	if err != nil {
		return fmt.Errorf("stderr pipe: %w", err)
	}

	remoteCmd := buildRemoteCommand(opts)

	if err := session.Start(remoteCmd); err != nil {
		return fmt.Errorf("start remote command: %w", err)
	}

	var wg sync.WaitGroup
	wg.Add(2)
	go streamLines(stdout, cb, &wg)
	go streamLines(stderr, cb, &wg)

	done := make(chan error, 1)
	go func() {
		wg.Wait()
		done <- session.Wait()
	}()

	select {
	case err := <-done:
		if err != nil {
			var exitMissing *ssh.ExitMissingError
			if errors.As(err, &exitMissing) {
				return fmt.Errorf("install.sh failed: the SSH connection was dropped before it finished (often the VPS's own package manager restarting a service mid-install, or a network blip) - check the server with `journalctl -u openflux-controlplane` and retry; install.sh is safe to re-run: %w", err)
			}
			return fmt.Errorf("install.sh failed: %w", err)
		}
		return nil
	case <-time.After(deployTimeout):
		session.Signal(ssh.SIGKILL)
		return fmt.Errorf("deploy timed out after %s", deployTimeout)
	}
}

func buildAuthMethod(target SSHTarget) (ssh.AuthMethod, error) {
	switch target.AuthMethod {
	case "key":
		var signer ssh.Signer
		var err error
		if target.Passphrase != "" {
			signer, err = ssh.ParsePrivateKeyWithPassphrase([]byte(target.PrivateKeyPEM), []byte(target.Passphrase))
		} else {
			signer, err = ssh.ParsePrivateKey([]byte(target.PrivateKeyPEM))
		}
		if err != nil {
			return nil, fmt.Errorf("parse private key: %w", err)
		}
		return ssh.PublicKeys(signer), nil
	case "password", "":
		return ssh.Password(target.Password), nil
	default:
		return nil, fmt.Errorf("unknown auth method %q", target.AuthMethod)
	}
}

// resultLinePrefix marks install.sh's one machine-readable summary line, reported via OnDeployResult instead of OnLog.
const resultLinePrefix = "OPENFLUX_DEPLOY_RESULT "

func streamLines(r io.Reader, cb Callback, wg *sync.WaitGroup) {
	defer wg.Done()
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if fields, ok := strings.CutPrefix(line, resultLinePrefix); ok {
			reportDeployResult(fields, cb)
			continue
		}
		cb.OnLog(line)
	}
}

func reportDeployResult(fields string, cb Callback) {
	values := make(map[string]string)
	for _, tok := range strings.Fields(fields) {
		key, value, ok := strings.Cut(tok, "=")
		if !ok {
			continue
		}
		values[key] = value
	}
	cb.OnDeployResult(values["panel_url"], values["admin_token"], values["node_token"])
}

func buildRemoteCommand(opts DeployOptions) string {
	scriptURL := opts.DeployScriptURL
	if scriptURL == "" {
		scriptURL = defaultDeployScriptURL
	}

	env := map[string]string{
		"REPO_URL":      opts.RepoURL,
		"GIT_REF":       opts.GitRef,
		"TLS_MODE":      opts.TLSMode,
		"DOMAIN":        opts.Domain,
		"LE_EMAIL":      opts.Email,
		"SERVER_IP":     opts.ServerIP,
		"ADMIN_TOKEN":   opts.AdminToken,
		"DB_PASSWORD":   opts.DBPassword,
		"REGISTER_NODE": boolToYN(opts.RegisterNode),
		"NODE_NAME":     opts.NodeName,
		"NODE_MAX_KEYS": strconv.Itoa(opts.NodeMaxKeys),
		"RUN_NODE_HERE": boolToYN(opts.RunNodeHere),
		// install.sh's WEB_PANEL prompt defaults to "y" but this exec has no controlling terminal; pinned to "n" until there is a UI for it.
		"WEB_PANEL": "n",
	}

	var b strings.Builder
	b.WriteString("set -e; ")
	// raw.githubusercontent.com caches a URL briefly; a unique query string per run defeats that so a just-shipped fix is not missed.
	fmt.Fprintf(&b, "curl -fsSL %s -o /tmp/openflux-install.sh; ", shellQuote(cacheBust(scriptURL)))
	for _, key := range []string{
		"REPO_URL", "GIT_REF", "TLS_MODE", "DOMAIN", "LE_EMAIL", "SERVER_IP",
		"ADMIN_TOKEN", "DB_PASSWORD", "REGISTER_NODE", "NODE_NAME", "NODE_MAX_KEYS", "RUN_NODE_HERE",
		"WEB_PANEL",
	} {
		v := env[key]
		if v == "" {
			continue // unset: install.sh's own defaults/prompts-skipped-if-blank logic applies
		}
		fmt.Fprintf(&b, "export %s=%s; ", key, shellQuote(v))
	}
	b.WriteString("bash /tmp/openflux-install.sh")

	return b.String()
}

func cacheBust(scriptURL string) string {
	sep := "?"
	if strings.Contains(scriptURL, "?") {
		sep = "&"
	}
	return fmt.Sprintf("%s%s_=%d", scriptURL, sep, time.Now().UnixNano())
}

func boolToYN(b bool) string {
	if b {
		return "y"
	}
	return "n"
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

type noopCallback struct{}

func (noopCallback) OnLog(string)                          {}
func (noopCallback) OnHostKeyFingerprint(string)           {}
func (noopCallback) OnDeployResult(string, string, string) {}
